apiVersion: v1
kind: Service #
metadata:
  name: simple-bank-api-service
spec: # spec ของ server
  selector:
    app: simple-bank-api # เอา label ของ deployment มาเลย
  ports:
    - protocol: TCP # http
      port: 80 # port ที่ service จะทำการ listening
      targetPort: 8080 # เนื่องจาก api container ของเรา export ที่ port ouh
    # เหมือนรับ incoming requests จาก port 80 แล้วส่งไปที่ 8080 ที่ที่ container เอาไว้รับ request นั้นเอง
  type: LoadBalancer
